In [1]:
import numpy as np 

a = np.matrix('1 1 1; 0 1 1; 0 0 1')  

b = np.matrix('7 5 3; 0 7 5; 0 0 7')  

c = a.dot(b)  

print(c) 

d = b.dot(a)  

print(d) 

g = c - d 

print(g) 

[[ 7 12 15]
 [ 0  7 12]
 [ 0  0  7]]
[[ 7 12 15]
 [ 0  7 12]
 [ 0  0  7]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [2]:
a = np.array([[-1, 2], [0, 1]]) 

power = np.linalg.matrix_power(a, 2) 

print(power) 

[[1 0]
 [0 1]]


In [3]:
a = np.matrix('5 8 -4; 6 9 -5; 4 7 -3') 

b = np.matrix('3 2 5; 4 -1 3; 9 6 5') 

c = a.dot(b) 

print(c) 

[[ 11 -22  29]
 [  9 -27  32]
 [ 13 -17  26]]


In [4]:
a = np.matrix('2 3 4; 1 0 6; 7 8 9') 

print(a) 

np.linalg.det(a) 

[[2 3 4]
 [1 0 6]
 [7 8 9]]


35.00000000000001

In [5]:
a = np.matrix('2 3 4 1; 1 2 3 4; 3 4 1 2; 4 1 2 3') 

print(a) 

np.linalg.det(a) 

[[2 3 4 1]
 [1 2 3 4]
 [3 4 1 2]
 [4 1 2 3]]


-160.00000000000009

In [6]:
a = np.matrix('1 2 2; 2 1 -2; 2 -2 1') 

a_inv = np.linalg.inv(a) 

print(a_inv) 

[[ 0.11111111  0.22222222  0.22222222]
 [ 0.22222222  0.11111111 -0.22222222]
 [ 0.22222222 -0.22222222  0.11111111]]


In [7]:
a = np.matrix('-2 3 1 -1; 3 2 1 4; 1 2 3 4; 0 2 3 3') 

rank = np.linalg.matrix_rank(a) 

print(rank) 

3
